version: '3.8'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - $DB_LOCAL_PATH:$DB_DOCKER_PATH
    depends_on:
      - kafka

  users_service:
    build: $AUTHORIZATION_SERVICE_LOCAL_PATH
    restart: unless-stopped
    environment:
      - PORT=$USERS_SERVICE_DOCKER_PORT
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DB_NAME=$MONGODB_DATABASE
      - COLLECTION_NAME=$USERS_COLLECTION
    volumes:
      - $USERS_SERVICE_LOCAL_PATH:$USERS_SERVICE_DOCKER_PATH
    ports:
      - $USERS_SERVICE_LOCAL_PORT:$USERS_SERVICE_DOCKER_PORT
    depends_on:
      - mongodb

  authorization_service:
    build: $AUTHORIZATION_SERVICE_LOCAL_PATH
    restart: unless-stopped
    environment:
      - PORT=$AUTHORIZATION_SERVICE_DOCKER_PORT
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DB_NAME=$MONGODB_DATABASE
      - COLLECTION_NAME=$AUTHENTICATION_COLLECTION
    volumes:
      - $AUTHORIZATION_SERVICE_LOCAL_PATH:$AUTHORIZATION_SERVICE_DOCKER_PATH
    ports:
      - $AUTHORIZATION_SERVICE_LOCAL_PORT:$AUTHORIZATION_SERVICE_DOCKER_PORT
      - 9229:9229
    depends_on:
      - mongodb

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      driver: none
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - $MONGOEXPRESS_LOCAL_PORT:$MONGOEXPRESS_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$ADMIN_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$ADMIN_CONFIG_BASICAUTH_PASSWORD
    depends_on:
      - mongodb
      